### PR TITLE
Rename Anidb.png to AniDB.png

### PR DESCRIPTION
**Pull request by eski-dev**
Fixes anidb rating overlay

## Description

At some point recently the image must have been updated with a slightly different syntax, and since the filename is case-sensitive the image could no longer be located.

Note: I'm on Ubuntu 22.04 using the official, master docker image of Kometa. I was able to verify the fix by simply renaming the file to "AniDB.png", though making the image search case-insensitive may be a more robust solution.

### Issues Fixed or Closed

- Fixes AniDB rating overlay

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code was submitted to the nightly branch of the repository.

### CODE REVIEW

**Comment by meisnate12** [comment]
where did you get the error from?

**Comment by eski-dev** [comment]
My logfiles, here's the relevant snippet:

```[2024-05-31 14:55:25,305] [builder.py:244]            [INFO]     |=============================== Validating Rating1Rotten Attributes ================================|
[2024-05-31 14:55:25,310] [plex.py:1055]              [DEBUG]    |                                                                                                    |
[2024-05-31 14:55:25,310] [plex.py:1058]              [DEBUG]    | Looking for: Rating1Rotten                                                                         |
[2024-05-31 14:55:25,311] [builder.py:436]            [DEBUG]    |                                                                                                    |
[2024-05-31 14:55:25,311] [builder.py:437]            [DEBUG]    | Validating Method: run_definition                                                                  |
[2024-05-31 14:55:25,311] [builder.py:440]            [DEBUG]    | Value: True                                                                                        |
[2024-05-31 14:55:25,311] [overlay.py:101]            [DEBUG]    |                                                                                                    |
[2024-05-31 14:55:25,311] [overlay.py:102]            [DEBUG]    | Validating Method: overlay                                                                         |
[2024-05-31 14:55:25,312] [overlay.py:103]            [DEBUG]    | Value: {'name': 'text(<<critic_rating>>)', 'default': 'rating/AniDB', 'group': 'rating1_group', 'weight': 100, 'horizontal_offset': 30, 'horizontal_align': 'left', 'vertical_offset': '-205', 'vertical_align': 'center', 'font': 'fonts/Inter-Bold.ttf', 'font_size': 63, 'font_color': '#FFFFFF', 'back_color': '#00000099', 'back_width': 160, 'back_height': 160, 'back_padding': 15, 'back_radius': 30, 'addon_offset': 15, 'addon_position': 'top'} |
[2024-05-31 14:55:25,320] [overlays.py:601]           [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/overlays.py", line 558, in compile_overlays                                       |
                                                                 |     builder = CollectionBuilder(self.config, overlay_file, k, v, library=self.library, overlay=True) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 508, in __init__                                                |
                                                                 |     self.overlay = Overlay(config, library, metadata, str(self.mapping_name), overlay_data, suppress, self.builder_level) |
                                                                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/overlay.py", line 196, in __init__                                                |
                                                                 |     raise Failed(f"Overlay Error: Overlay Image not found at: {os.path.abspath(os.path.join(images_path, temp_path))}") |
                                                                 | modules.util.Failed: Overlay Error: Overlay Image not found at: /defaults/overlays/images/rating/AniDB.png |
                                                                 |                                                                                                    |
[2024-05-31 14:55:25,322] [overlays.py:602]           [ERROR]    | Overlay Error: Overlay Image not found at: /defaults/overlays/images/rating/AniDB.png              |```

**Comment by meisnate12** [comment]
so its actually already named AniDB 

https://github.com/Kometa-Team/Kometa/blob/nightly/defaults/overlays/images/rating/AniDB.png

it must not have pulled in the changes to your local

**Comment by eski-dev** [comment]
Ah, I didn't check to see if nightly was already updated. I pulled the master image for the first time just last night. Apologies!

Should I just close my PR, then?

**Comment by YozoraXCII** [comment]
Closing

**Pull request closed without merging**
