### PR TITLE
added default headers for http requests in config.py

### PR DESCRIPTION
**Pull request by Glenn332**
There was an issue with http requests going to IMDb, this should fix it ;)

### CODE REVIEW

**Comment by holl595** [comment]
Why has this been closed and not merged in?

**Comment by JohnFawkes** [comment]
> Why has this been closed and not merged in?

https://github.com/meisnate12/Plex-Meta-Manager/commit/b37d1ebb0458f9e1ef5d99b3aac9487ceab5cb0e

Sohjiro added this ^ to fix imdb

**Comment by Glenn332** [comment]
> Why has this been closed and not merged in?

The owner created a fix [commit](https://github.com/meisnate12/Plex-Meta-Manager/commit/b37d1ebb0458f9e1ef5d99b3aac9487ceab5cb0e). However this only solves it for the Plex module, my fix was more global. There were mentions of other services also requiring a custom user agent instead of the default the python package requests comes with. Those requests are easily blocked.

**Comment by holl595** [comment]
It looks like it’s not resolved the issue with collections, another issue appears to have been raised here https://github.com/meisnate12/Plex-Meta-Manager/issues/1496

**Comment by Glenn332** [comment]
> It looks like it’s not resolved the issue with collections, another issue appears to have been raised here #1496

This PR was never merged in

**Comment by holl595** [comment]
Yes, closing this instead of merging it probably wasn’t the best choice

**Comment by YozoraXCII** [comment]
> Yes, closing this instead of merging it probably wasn’t the best choice

As mentioned in #1496, IMDb are currently going through and re-structuring their entire website, they chose to roll it out slowly rather than all-in-one. This PR will not fix that, it will be a case of PMM playing catch-up every time IMDb pushes new versions of new pages.

**Comment by Glenn332** [comment]
> Yes, closing this instead of merging it probably wasn’t the best choice

Please keep in mind that only charts break when scraping them now, do normal lists still work for you?

**Pull request closed without merging**
