### PR TITLE
movies collections template

### PR DESCRIPTION
**Pull request by Glasti1**
This is my Movies.yml i would like to share.

It conists of 6 Templates.

A mix of collections with plex_search and TMDb lists.

Edit: Sorry my first PR!

### CODE REVIEW

**Comment by Glasti1** [comment]
I see, i didnt change the `Holidays` sort_title.. the rest works. i tried to merge the Holidays Collections into the Genre collections.

Will go through it some more to see if i can find some more mistakes.. 

Edit: tested it again, i see what you mean! That's why i didnt work.

**Comment by meisnate12** [comment]
You're fine I'm glad you wanna share your metadata config but I set up a different repo for user configs you can find it at this link https://github.com/meisnate12/Plex-Meta-Manager-Configs fork that repo and submit your Metadata config there

**Comment by Glasti1** [comment]
> You're fine I'm glad you wanna share your metadata config but I set up a different repo for user configs you can find it at this link https://github.com/meisnate12/Plex-Meta-Manager-Configs fork that repo and submit your Metadata config there

AAHH!! ill make a PR there in a minute! Thanks for you work! Really enjoying it. I am happy to try to make something else if you want something specific.

**Comment by meisnate12** [comment]
I know people are waiting for me to finish my anime and tv shows metadata files but i just havent had the time to so if you do either all i ask is that you share!

**Comment by Glasti1** [comment]
I do not do Anime, but i am happy to start chipping away on a TV list..

What Collections would you want to see in the TV Collections?

**Pull request closed without merging**
