### PR TITLE
Hotfix - letterboxd.py

### LINKED ISSUE #1560: Letterboxd Lists now Error: Failed to establish a new connection: [Errno -2] Name does not resolve
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

Starting from today - any Collections that use letterboxd_list or letterboxd_list_details result in connection errors - Unknown Error: HTTPSConnectionPool(redacted): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5a85a37150>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

Possibly caused by the Letterboxd API not shifting into private beta - https://letterboxd.com/api-beta/ - looks like you need to apply to get access to this - assuming this is the cause of the new issue.

### Relevant Collection/Overlay/Playlist Definition

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by jack2game**
## Description

Hotfix for error when pulling from Letterboxd list.

### Issues Fixed or Closed

- Fixes #1560 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code was submitted to the nightly branch of the repository.

### CODE REVIEW

**Comment by markmarz** [comment]
Any ETA when this fix will be merged into nightly?
Bug persists.

**Comment by sych0** [comment]
same issue here

**Comment by YozoraXCII** [comment]
> Any ETA when this fix will be merged into nightly?
> Bug persists.

It was merged

Can you provide an updated log file if you are still having issue

**Comment by YozoraXCII** [comment]
> Any ETA when this fix will be merged into nightly?
> Bug persists.

If you're on nighlty99 or above can you provide an updated log

**Comment by markmarz** [comment]
Sorry, I just checked again and I screwed up. I downloaded nightly but my
run script still executed the docker container tagged latest.

All's well after executing docker container with tag nightly.

**Pull request closed without merging**
