### PR TITLE
Add a rebrand page linked front and center

### PR DESCRIPTION
**Pull request by chazlarson**
## Description

Puts a "here's what you have to do" page front and center

## Type of Change

- [X] Documentation change (non-code changes affecting only the wiki)

## Checklist

- [X] My code was submitted to the nightly branch of the repository.

### CODE REVIEW

**Comment by chazlarson** [comment]
the spellcheck failure here is addressed in #2038

**Comment by YozoraXCII** [comment]
> the spellcheck failure here is addressed in #2038

There is more than one failure, you maybe didn't scroll up and only saw the last one?

These are picked up as misspelled:

`uncompress`
`PMM`
`rebrand`
`PlexMetaManager`

**Comment by YozoraXCII** [comment]
Heading elements [`<h1>`] are not supported as part of a hyperlink, and as a result nothing is displayed.

This:

```

[<h1>WHAT IS THIS KOMETA THING AND HOW DO I UPGRADE FROM PLEX META MANAGER?</h1>](kometa/guides/rebrand.md)

Kometa (formerly known as Plex Meta Manager) is a powerful tool designed to give you complete control over your media libraries. With Kometa, you can take your customization to the next level, with granular control over metadata, collections, overlays, and much more.

[WHAT IS THIS KOMETA THING AND HOW DO I UPGRADE FROM PLEX META MANAGER?](kometa/guides/rebrand.md)

Transform your media library with Kometa and discover its full potential! Connect to third-party services like TMDb, Trakt, and IMDb, among others, to create one-of-a-kind collections, overlays and more. Your media library will stand out and be tailored to your specific needs.

```

produces this when built, notice the first one is completely absent.

image

I don't really like having that front and center of the homepage, I would prefer an admonition, but if it needs to be an uppercase statement then I would also consider rewording this to make it clear that's a hyperlink "WHAT IS KOMETA AND HOW DO I UPGRADE FROM PLEX META MANAGER? CLICK HERE FOR MORE INFO" or something.

**Comment by chazlarson** [comment]
Well, this apparently wasn't based on nightly, so I'm going to try this again.

**Comment by YozoraXCII** [comment]
Just to add to my previous reply, I think an admonition looks more "professional":

image

If you want to use it (happy for it to be reworded):

```
!!! info "What Happened to Plex Meta Manager?"

    On April 25th 2024, the Plex Meta Manager name was officially retired and replaced with Kometa. This change was essential to avoid a trademark issue with Plex.

    **If you are still using Plex Meta Manager and are unsure how to upgrade to Kometa, [click here to follow our guide](kometa/guides/rebrand.md)**
```

**Pull request closed without merging**
