### PR TITLE
fix parental labels

### PR DESCRIPTION
**Pull request by meisnate12**
## Description

fix parental labels

### Issues Fixed or Closed

- Fixes #(issue)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Updated the CHANGELOG with the changes

### CODE REVIEW

**Comment by miaLDN** [comment]
Does this fix the parental labels?  :)

I'm currently debugging them here, maybe you've fixed it already :)

**Comment by miaLDN** [comment]
Thank You!  This fixes the IMDb Parental Ratings.  I was working on an overlay, and spent a weekend wondering why I wasn't getting IMDb Parental Labels added!

I copied your patch into my local branch, and it looks good :)

**Comment by antwanchild** [comment]
> Does this fix the parental labels? :)
> 
> I'm currently debugging them here, maybe you've fixed it already :)

that's literally the name of the PR.  But this is not currently pushed to nightly.

**Comment by miaLDN** [comment]
I ran my locally patched code with this change; and tada, it added 380 new labels to my media:

``` txt
[2024-10-31 00:36:21,468] [operations.py:910]         [INFO]     |========================================== Batch Updates ===========================================|
[2024-10-31 00:36:21,468] [operations.py:911]         [INFO]     |                                                                                                    |
[2024-10-31 00:36:21,484] [operations.py:924]         [INFO]     | Batch Label Update (1/20): Adding Alcohol:Mild to 33 Movies                                        |
[2024-10-31 00:36:22,503] [operations.py:924]         [INFO]     | Batch Label Update (2/20): Adding Alcohol:Moderate to 20 Movies                                    |
[2024-10-31 00:36:23,820] [operations.py:924]         [INFO]     | Batch Label Update (3/20): Adding Alcohol:None to 18 Movies                                        |
[2024-10-31 00:36:26,041] [operations.py:924]         [INFO]     | Batch Label Update (4/20): Adding Alcohol:Severe to 2 Movies                                       |
[2024-10-31 00:36:26,883] [operations.py:924]         [INFO]     | Batch Label Update (5/20): Adding Frightening:Mild to 23 Movies                                    |
[2024-10-31 00:36:27,851] [operations.py:924]         [INFO]     | Batch Label Update (6/20): Adding Frightening:Moderate to 15 Movies                                |
[2024-10-31 00:36:29,291] [operations.py:924]         [INFO]     | Batch Label Update (7/20): Adding Frightening:None to 13 Movies                                    |
[2024-10-31 00:36:30,284] [operations.py:924]         [INFO]     | Batch Label Update (8/20): Adding Frightening:Severe to 15 Movies                                  |
[2024-10-31 00:36:31,212] [operations.py:924]         [INFO]     | Batch Label Update (9/20): Adding Nudity:Mild to 41 Movies                                         |
[2024-10-31 00:36:32,524] [operations.py:924]         [INFO]     | Batch Label Update (10/20): Adding Nudity:Moderate to 19 Movies                                    |
[2024-10-31 00:36:33,807] [operations.py:924]         [INFO]     | Batch Label Update (11/20): Adding Nudity:None to 47 Movies                                        |
[2024-10-31 00:36:35,161] [operations.py:924]         [INFO]     | Batch Label Update (12/20): Adding Nudity:Severe to 9 Movies                                       |
[2024-10-31 00:36:36,713] [operations.py:924]         [INFO]     | Batch Label Update (13/20): Adding Profanity:Mild to 20 Movies                                     |
[2024-10-31 00:36:37,841] [operations.py:924]         [INFO]     | Batch Label Update (14/20): Adding Profanity:Moderate to 34 Movies                                 |
[2024-10-31 00:36:38,866] [operations.py:924]         [INFO]     | Batch Label Update (15/20): Adding Profanity:None to 14 Movies                                     |
[2024-10-31 00:36:40,082] [operations.py:924]         [INFO]     | Batch Label Update (16/20): Adding Profanity:Severe to 11 Movies                                   |
[2024-10-31 00:36:41,178] [operations.py:924]         [INFO]     | Batch Label Update (17/20): Adding Violence:Mild to 25 Movies                                      |
[2024-10-31 00:36:42,234] [operations.py:924]         [INFO]     | Batch Label Update (18/20): Adding Violence:Moderate to 25 Movies                                  |
[2024-10-31 00:36:43,591] [operations.py:924]         [INFO]     | Batch Label Update (19/20): Adding Violence:None to 15 Movies                                      |
[2024-10-31 00:36:44,847] [operations.py:924]         [INFO]     | Batch Label Update (20/20): Adding Violence:Severe to 22 Movies                                    |
[2024-10-31 00:36:46,096] [operations.py:924]         [INFO]     | Batch Label Update (1/2): Removing Nudity:Moderate from 1 Movie                                    |
[2024-10-31 00:36:46,949] [operations.py:924]         [INFO]     | Batch Label Update (2/2): Removing Nudity:Severe from 1 Movie                                      |
[2024-10-31 00:36:47,894] [operations.py:932]         [INFO]     | Batch Audience Rating Update (1/3): 1 Movie updated to 8.3                                         |
[2024-10-31 00:36:47,909] [operations.py:1068]        [INFO]     |                                                                                                    |

```

**Comment by antwanchild** [comment]
> I ran my locally patched code with this change; and tada, it added 380 new labels to my media:
> 
> ```
> [2024-10-31 00:36:21,468] [operations.py:910]         [INFO]     |========================================== Batch Updates ===========================================|
> [2024-10-31 00:36:21,468] [operations.py:911]         [INFO]     |                                                                                                    |
> [2024-10-31 00:36:21,484] [operations.py:924]         [INFO]     | Batch Label Update (1/20): Adding Alcohol:Mild to 33 Movies                                        |
> [2024-10-31 00:36:22,503] [operations.py:924]         [INFO]     | Batch Label Update (2/20): Adding Alcohol:Moderate to 20 Movies                                    |
> [2024-10-31 00:36:23,820] [operations.py:924]         [INFO]     | Batch Label Update (3/20): Adding Alcohol:None to 18 Movies                                        |
> [2024-10-31 00:36:26,041] [operations.py:924]         [INFO]     | Batch Label Update (4/20): Adding Alcohol:Severe to 2 Movies                                       |
> [2024-10-31 00:36:26,883] [operations.py:924]         [INFO]     | Batch Label Update (5/20): Adding Frightening:Mild to 23 Movies                                    |
> [2024-10-31 00:36:27,851] [operations.py:924]         [INFO]     | Batch Label Update (6/20): Adding Frightening:Moderate to 15 Movies                                |
> [2024-10-31 00:36:29,291] [operations.py:924]         [INFO]     | Batch Label Update (7/20): Adding Frightening:None to 13 Movies                                    |
> [2024-10-31 00:36:30,284] [operations.py:924]         [INFO]     | Batch Label Update (8/20): Adding Frightening:Severe to 15 Movies                                  |
> [2024-10-31 00:36:31,212] [operations.py:924]         [INFO]     | Batch Label Update (9/20): Adding Nudity:Mild to 41 Movies                                         |
> [2024-10-31 00:36:32,524] [operations.py:924]         [INFO]     | Batch Label Update (10/20): Adding Nudity:Moderate to 19 Movies                                    |
> [2024-10-31 00:36:33,807] [operations.py:924]         [INFO]     | Batch Label Update (11/20): Adding Nudity:None to 47 Movies                                        |
> [2024-10-31 00:36:35,161] [operations.py:924]         [INFO]     | Batch Label Update (12/20): Adding Nudity:Severe to 9 Movies                                       |
> [2024-10-31 00:36:36,713] [operations.py:924]         [INFO]     | Batch Label Update (13/20): Adding Profanity:Mild to 20 Movies                                     |
> [2024-10-31 00:36:37,841] [operations.py:924]         [INFO]     | Batch Label Update (14/20): Adding Profanity:Moderate to 34 Movies                                 |
> [2024-10-31 00:36:38,866] [operations.py:924]         [INFO]     | Batch Label Update (15/20): Adding Profanity:None to 14 Movies                                     |
> [2024-10-31 00:36:40,082] [operations.py:924]         [INFO]     | Batch Label Update (16/20): Adding Profanity:Severe to 11 Movies                                   |
> [2024-10-31 00:36:41,178] [operations.py:924]         [INFO]     | Batch Label Update (17/20): Adding Violence:Mild to 25 Movies                                      |
> [2024-10-31 00:36:42,234] [operations.py:924]         [INFO]     | Batch Label Update (18/20): Adding Violence:Moderate to 25 Movies                                  |
> [2024-10-31 00:36:43,591] [operations.py:924]         [INFO]     | Batch Label Update (19/20): Adding Violence:None to 15 Movies                                      |
> [2024-10-31 00:36:44,847] [operations.py:924]         [INFO]     | Batch Label Update (20/20): Adding Violence:Severe to 22 Movies                                    |
> [2024-10-31 00:36:46,096] [operations.py:924]         [INFO]     | Batch Label Update (1/2): Removing Nudity:Moderate from 1 Movie                                    |
> [2024-10-31 00:36:46,949] [operations.py:924]         [INFO]     | Batch Label Update (2/2): Removing Nudity:Severe from 1 Movie                                      |
> [2024-10-31 00:36:47,894] [operations.py:932]         [INFO]     | Batch Audience Rating Update (1/3): 1 Movie updated to 8.3                                         |
> [2024-10-31 00:36:47,909] [operations.py:1068]        [INFO]     |                                                                                                    |
> ```

yep, it's available using the docker tag. and will eventually be pushed to nightly and then develop and master

**Comment by miaLDN** [comment]
> > Does this fix the parental labels? :)
> > I'm currently debugging them here, maybe you've fixed it already :)
> 
> that's literally the name of the PR. But this is not currently pushed to nightly.

Indeed. I spotted by chance; as I started debugging them myself - need for my overlay work.

**Comment by miaLDN** [comment]
@antwanchild I'd assumed I was doing something wrong with my Kometa `config.yml`, so had been struggling to get the labels working for a while.  I hadn't wanted to raise a bug, until I was 100% sure it wasn't a fault here...  :)

**Comment by miaLDN** [comment]
Just a follow-up; this PR also fixes the problem I had with TV Shows.  Until this patch, I literally had zero IMDb Parental Labels in my TV Shows Libraries.

I can see it adding them *all* now!


@antwanchild @meisnate12 thank you :)  I've been delayed on my Overlay work for trying to get these labels working.

**Pull request merged**
