### PR TITLE
Update languages.yml

### PR DESCRIPTION
**Pull request by adam-pope-arup**
## Description

Added Somali, Wolof, Inuit, and Mayan as audio/subtitle languages

## Type of Change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ Y] My code was submitted to the nightly branch of the repository.

### CODE REVIEW

**Comment by YozoraXCII** [comment]
Not ready to merge:
- Missing doc updates which were in #1534 
- Doesn't contain any flag images for most of the new languages

Messaged on Discord to discuss.

**Comment by YozoraXCII** [comment]
Ready to be merged along with #1537

**Comment by YozoraXCII** [comment]
Ready to be merged along with #1537

**Comment by meisnate12** [comment]
still no flags for Wolof, Inuit, and Mayan

**Pull request merged**
