### PR TITLE
Dockerfile: Added tini.

### LINKED ISSUE #743: Feature Request: Use tini for the docker container.
**Is your feature request related to a problem? Please describe.**
Docker container does not exit gracefully, use something like https://github.com/krallin/tini to properly shut things down. Instead of having to wait for docker to force kill the container.

**Describe the solution you'd like**
Use tini or something similar.

**Describe alternatives you've considered**
Not sure it applies.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by saltydk**
## Description

Added tini so that the container should close gracefully better instead of sometimes timing out and docker force kills it.

### Issues Fixed or Closed

- Fixes #743

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by meisnate12** [comment]
could you rebase on the nightly branch i wanna test this out there first

**Comment by saltydk** [comment]
done

**Comment by YozoraXCII** [comment]
Using saltbox to test this, the container starts and shuts down successfully now (it used to take 2 mins+, it now shuts down in about 1 second).

The docker run command is failing with the following:

docker run --rm -it --network=saltbox -v /opt/plex-meta-manager:/config meisnate12/plex-meta-manager:nightly --run
[FATAL tini (8)] exec --run failed: No such file or directory

**Comment by saltydk** [comment]
Maybe the argument isn't getting passed to python. I'll look at it again.

**Comment by saltydk** [comment]
Should be fixed in https://github.com/meisnate12/Plex-Meta-Manager/pull/755

**Comment by YozoraXCII** [comment]
> Should be fixed in #755

can confirm I am now able to run with the --run flag.

**Pull request merged**
